//! Assembles the real AP startup trampoline (`src/smp/ap_trampoline.asm`)
//! with `nasm` into a flat binary, embedded into the kernel via
//! `include_bytes!` (see `smp.rs`).
//!
//! Why a real external assembler rather than Rust's `global_asm!`: the
//! trampoline genuinely needs to run 16-bit real-mode code (an AP starts
//! executing with no GDT, no paging, real-mode addressing only — see
//! `ap_trampoline.asm`'s module docs), and `nasm` is a real, purpose-built,
//! long-established tool for exactly that, rather than pushing LLVM's
//! integrated assembler through mode-switching directives it wasn't
//! primarily designed to exercise. `ORG 0x8000` in the `.asm` file makes
//! every label in it resolve to a real absolute address already assuming
//! the assembled bytes are loaded at physical `0x8000` — `smp.rs` copies
//! this exact blob there before ever starting the AP.
//!
//! This build script also parses `nasm`'s own `[map all ...]` output (real
//! symbol addresses nasm itself computed from the `ORG`, not hand-counted
//! byte offsets) for the three real data-slot addresses (`ap_cr3`,
//! `ap_stack_top`, `ap_entry_addr`) the BSP pokes into the trampoline page
//! before sending the SIPI, and the trampoline's own start/end addresses —
//! emitting them as real Rust `const`s (`OUT_DIR/ap_trampoline_symbols.rs`)
//! so `smp.rs` never has to duplicate or hand-recompute them.

use std::env;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));

    let asm_path = manifest_dir.join("src/smp/ap_trampoline.asm");
    println!("cargo:rerun-if-changed={}", asm_path.display());

    let bin_path = out_dir.join("ap_trampoline.bin");
    let map_path = out_dir.join("ap_trampoline.map");

    let status = Command::new("nasm")
        .current_dir(&out_dir)
        .arg("-f")
        .arg("bin")
        .arg(&asm_path)
        .arg("-o")
        .arg(&bin_path)
        .status()
        .expect(
            "failed to run `nasm` — the real AP trampoline (src/smp/ap_trampoline.asm) is \
             assembled by a real external assembler, not Rust's global_asm!; install nasm \
             (e.g. `scoop install nasm` / apt/`nasm`) and ensure it's on PATH",
        );
    assert!(status.success(), "nasm failed to assemble {}", asm_path.display());
    assert!(map_path.exists(), "nasm did not produce the expected map file at {}", map_path.display());

    let map_text = std::fs::read_to_string(&map_path).expect("failed to read nasm map file");
    let mut symbols = std::collections::HashMap::new();
    // Real nasm map-file symbol lines look like:
    //             8000              8000  ap_trampoline_start
    // (Real, Virtual, Name — all three space-separated, hex without a 0x prefix.)
    for line in map_text.lines() {
        let mut parts = line.split_whitespace();
        let (Some(real), Some(_virtual), Some(name)) = (parts.next(), parts.next(), parts.next()) else {
            continue;
        };
        if parts.next().is_some() {
            continue; // not a two-hex-plus-name symbol line
        }
        if let Ok(addr) = u64::from_str_radix(real, 16) {
            symbols.insert(name.to_string(), addr);
        }
    }

    let needed = [
        "ap_trampoline_start",
        "ap_trampoline_end",
        "ap_cr3",
        "ap_stack_top",
        "ap_entry_addr",
    ];
    let mut generated = String::new();
    generated.push_str("// Generated by build.rs from src/smp/ap_trampoline.asm's real nasm map output.\n");
    for name in needed {
        let addr = *symbols
            .get(name)
            .unwrap_or_else(|| panic!("nasm map file for ap_trampoline.asm did not contain symbol `{name}`"));
        generated.push_str(&format!("pub const {}: u64 = {:#x};\n", name.to_uppercase(), addr));
    }

    let symbols_rs_path = out_dir.join("ap_trampoline_symbols.rs");
    std::fs::write(&symbols_rs_path, generated).expect("failed to write ap_trampoline_symbols.rs");

    println!("cargo:rustc-env=AP_TRAMPOLINE_BIN={}", bin_path.display());
}
